### ISSUE TITLE
Modules Load Problems (Autopsy 4.18.0)

### ISSUE THREAD

**Issue by Rackus87** [sleuthkit/autopsy_addon_modules#15]
Hello Sir,

I downloaded autopsy_addon_modules-master.zip and extracted then I copied to AppData\Roaming\autopsy\python_modules.
But when I analyzed the evidence the modules does not show up in my options. Please advise. 

Thanks in advance.

**Comment by markmckinnon** [comment]
This repository is a resource that points to where Autopsy modules reside they do not reside in this repository.  You will need to look at all the different available modules and where they reside and download them from where this repo states they are.  Closing this issue as complete., if you feel that this issue was not resolved then please reopen this issue.
